community:
    githubFeeds:
        - https://github.com/ppi/framework/commits/2.1.atom
        - https://github.com/ppi/skeletonapp/commits/2.1.atom
        - https://github.com/ppi/website/commits/master.atom

    twitterUsername: ppi_framework

docs:
    pages:
        - index
        - getting_started
        - application
        - controllers
        - modules
        - routing
        - templating

downloads:
    base_path: ./downloads/
    public_base_path: ./public/downloads/
    items:
        -
            id: 1
            name: "Skeleton Application - Version 2.1.1"
            url: "https://github.com/ppi/skeletonapp/archive/2.1.1.tar.gz"
            version: "2.1.1"
            date_released: "2015-02-07"

        -
            id: 2
            name: "Framework - Version 2.1.1"
            url: "https://github.com/ppi/framework/archive/2.1.1.tar.gz"
            version: "2.1.1"
            date_released: "2015-02-07"
